### ISSUE TITLE
Return Values are Ambiguous

### ISSUE THREAD

**Issue by ghost** [EntireTwix/CCash#12]
Return values from multiple endpoints, especially from sending funds, are very ambiguous. It is difficult to tell what went wrong when errors are in binary format. Thus, I suggest a new error system in which number codes are utilized. This will not only be easy to implement at minimal performance cost but will also increase code clarity and decrease the aforementioned ambiguity.

**Comment by ghost** [comment]
I understand that you have provided functions to check whether passwords or the user is valid, as well as to check balance, yet these come at a large performance penalty for connected serves to constantly use as checking mechanisms. I believe that, despite your philosophy of keeping the server as light as possible, this would be an excellent feature with minimal performance costs.

**Comment by EntireTwix** [comment]
yes I very much agree
