### ISSUE TITLE
I don't see enough Rust

### ISSUE THREAD

**Issue by STBoyden** [EntireTwix/CCash#4]
Let's just rewrite everything in Rust shall we?

**Comment by Soverclysm** [comment]
> Let's just rewrite everything in Rust shall we?

True this is a fantastic idea. Then the code will rust away haha get it because iron rusts

**Comment by STBoyden** [comment]
I wasn't seeing enough movement

**Comment by EntireTwix** [comment]
Do it yourself u lazy fucks!

**Comment by Soverclysm** [comment]
> Do it yourself u lazy fucks!

That's a dumb fucking idea because I don't want to now you do it
